/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as SongsNewRouteImport } from './routes/songs/new'
import { Route as SongsSongIdIndexRouteImport } from './routes/songs/$songId/index'
import { Route as SongsSongIdVersionsNewRouteImport } from './routes/songs/$songId/versions/new'
import { Route as SongsSongIdVersionsVersionIdRouteImport } from './routes/songs/$songId/versions/$versionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsNewRoute = SongsNewRouteImport.update({
  id: '/songs/new',
  path: '/songs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdIndexRoute = SongsSongIdIndexRouteImport.update({
  id: '/songs/$songId/',
  path: '/songs/$songId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdVersionsNewRoute = SongsSongIdVersionsNewRouteImport.update({
  id: '/songs/$songId/versions/new',
  path: '/songs/$songId/versions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdVersionsVersionIdRoute =
  SongsSongIdVersionsVersionIdRouteImport.update({
    id: '/songs/$songId/versions/$versionId',
    path: '/songs/$songId/versions/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/songs/new': typeof SongsNewRoute
  '/songs/': typeof SongsIndexRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/versions/$versionId': typeof SongsSongIdVersionsVersionIdRoute
  '/songs/$songId/versions/new': typeof SongsSongIdVersionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/songs/new': typeof SongsNewRoute
  '/songs': typeof SongsIndexRoute
  '/songs/$songId': typeof SongsSongIdIndexRoute
  '/songs/$songId/versions/$versionId': typeof SongsSongIdVersionsVersionIdRoute
  '/songs/$songId/versions/new': typeof SongsSongIdVersionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/songs/new': typeof SongsNewRoute
  '/songs/': typeof SongsIndexRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/versions/$versionId': typeof SongsSongIdVersionsVersionIdRoute
  '/songs/$songId/versions/new': typeof SongsSongIdVersionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/songs/new'
    | '/songs/'
    | '/songs/$songId/'
    | '/songs/$songId/versions/$versionId'
    | '/songs/$songId/versions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/songs/new'
    | '/songs'
    | '/songs/$songId'
    | '/songs/$songId/versions/$versionId'
    | '/songs/$songId/versions/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/songs/new'
    | '/songs/'
    | '/songs/$songId/'
    | '/songs/$songId/versions/$versionId'
    | '/songs/$songId/versions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SongsNewRoute: typeof SongsNewRoute
  SongsIndexRoute: typeof SongsIndexRoute
  SongsSongIdIndexRoute: typeof SongsSongIdIndexRoute
  SongsSongIdVersionsVersionIdRoute: typeof SongsSongIdVersionsVersionIdRoute
  SongsSongIdVersionsNewRoute: typeof SongsSongIdVersionsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/new': {
      id: '/songs/new'
      path: '/songs/new'
      fullPath: '/songs/new'
      preLoaderRoute: typeof SongsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/': {
      id: '/songs/$songId/'
      path: '/songs/$songId'
      fullPath: '/songs/$songId/'
      preLoaderRoute: typeof SongsSongIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/versions/new': {
      id: '/songs/$songId/versions/new'
      path: '/songs/$songId/versions/new'
      fullPath: '/songs/$songId/versions/new'
      preLoaderRoute: typeof SongsSongIdVersionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/versions/$versionId': {
      id: '/songs/$songId/versions/$versionId'
      path: '/songs/$songId/versions/$versionId'
      fullPath: '/songs/$songId/versions/$versionId'
      preLoaderRoute: typeof SongsSongIdVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SongsNewRoute: SongsNewRoute,
  SongsIndexRoute: SongsIndexRoute,
  SongsSongIdIndexRoute: SongsSongIdIndexRoute,
  SongsSongIdVersionsVersionIdRoute: SongsSongIdVersionsVersionIdRoute,
  SongsSongIdVersionsNewRoute: SongsSongIdVersionsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
