// TanStack Query hooks for GraphQL operations
// These hooks use the typed documents generated by codegen

import {
  useQuery,
  useMutation,
  useQueryClient,
  UseQueryOptions,
  UseMutationOptions,
} from "@tanstack/react-query";
import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import {
  executeGraphQL,
  FetcherOptions,
  GraphQLClientError,
  NetworkError,
} from "./fetcher";

// ============================================================================
// Generic Hooks
// ============================================================================

/**
 * Generic hook for GraphQL queries with full type inference.
 *
 * @example
 * ```ts
 * import { SongsDocument, SongsQuery } from '@/graphql/generated/graphql';
 *
 * const { data, isLoading, error } = useGraphQLQuery(
 *   ['songs'],
 *   SongsDocument
 * );
 * // data is typed as SongsQuery
 * ```
 */
export function useGraphQLQuery<TResult, TVariables>(
  queryKey: readonly unknown[],
  document: TypedDocumentNode<TResult, TVariables>,
  variables?: TVariables,
  options?: Omit<
    UseQueryOptions<TResult, GraphQLClientError | NetworkError>,
    "queryKey" | "queryFn"
  > &
    FetcherOptions,
) {
  const { requireAuth, headers, signal, ...queryOptions } = options ?? {};

  return useQuery<TResult, GraphQLClientError | NetworkError>({
    queryKey,
    queryFn: ({ signal: querySignal }) =>
      executeGraphQL(document, variables, {
        requireAuth,
        headers,
        signal: signal ?? querySignal,
      }),
    ...queryOptions,
  });
}

/**
 * Generic hook for GraphQL mutations with full type inference.
 *
 * @example
 * ```ts
 * import { CreateSongDocument } from '@/graphql/generated/graphql';
 *
 * const mutation = useGraphQLMutation(CreateSongDocument, {
 *   onSuccess: (data) => {
 *     // data is typed as CreateSongMutation
 *   },
 * });
 *
 * mutation.mutate({ input: { title: 'New Song', artist: 'Artist' } });
 * ```
 */
export function useGraphQLMutation<TResult, TVariables>(
  document: TypedDocumentNode<TResult, TVariables>,
  options?: Omit<
    UseMutationOptions<TResult, GraphQLClientError | NetworkError, TVariables>,
    "mutationFn"
  > &
    FetcherOptions,
) {
  const { requireAuth, headers, signal, ...mutationOptions } = options ?? {};

  return useMutation<TResult, GraphQLClientError | NetworkError, TVariables>({
    mutationFn: (variables) =>
      executeGraphQL(document, variables, { requireAuth, headers, signal }),
    ...mutationOptions,
  });
}

// ============================================================================
// Query Key Factories
// ============================================================================

/**
 * Centralized query key factory for cache management.
 */
export const queryKeys = {
  // Songs
  songs: {
    all: ["songs"] as const,
    lists: () => [...queryKeys.songs.all, "list"] as const,
    list: (filters?: Record<string, unknown>) =>
      [...queryKeys.songs.lists(), filters] as const,
    details: () => [...queryKeys.songs.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.songs.details(), id] as const,
  },

  // Versions
  versions: {
    all: ["versions"] as const,
    details: () => [...queryKeys.versions.all, "detail"] as const,
    detail: (id: string) => [...queryKeys.versions.details(), id] as const,
    bySong: (songId: string) =>
      [...queryKeys.versions.all, "bySong", songId] as const,
  },

  // Section Notes
  notes: {
    all: ["notes"] as const,
    byVersion: (versionId: string) =>
      [...queryKeys.notes.all, "byVersion", versionId] as const,
  },

  // Sync
  sync: {
    all: ["sync"] as const,
    pull: (cursor?: string | null) =>
      [...queryKeys.sync.all, "pull", cursor] as const,
  },

  // User
  user: {
    me: ["user", "me"] as const,
  },

  // Health
  health: ["health"] as const,
} as const;

// ============================================================================
// Cache Invalidation Helpers
// ============================================================================

/**
 * Hook for invalidating related queries after mutations.
 */
export function useInvalidateQueries() {
  const queryClient = useQueryClient();

  return {
    /**
     * Invalidate all song-related queries.
     */
    invalidateSongs: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.songs.all });
    },

    /**
     * Invalidate a specific song and its versions.
     */
    invalidateSong: (songId: string) => {
      queryClient.invalidateQueries({
        queryKey: queryKeys.songs.detail(songId),
      });
      queryClient.invalidateQueries({
        queryKey: queryKeys.versions.bySong(songId),
      });
    },

    /**
     * Invalidate all version-related queries.
     */
    invalidateVersions: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.versions.all });
    },

    /**
     * Invalidate a specific version and its notes.
     */
    invalidateVersion: (versionId: string) => {
      queryClient.invalidateQueries({
        queryKey: queryKeys.versions.detail(versionId),
      });
      queryClient.invalidateQueries({
        queryKey: queryKeys.notes.byVersion(versionId),
      });
    },

    /**
     * Invalidate all sync-related queries.
     */
    invalidateSync: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.sync.all });
    },

    /**
     * Invalidate everything after a full sync.
     */
    invalidateAll: () => {
      queryClient.invalidateQueries();
    },
  };
}
